-- This migration is intentionally empty.
-- The schedule table was already created in V9__CREATE_SCHEDULE_TABLE.sql,
-- and the duplicate foreign keys are not required here.
-- The M:N relationship itself is created in V11__CREATE_SCHEDULE_CANDIDATES.sql.
